### ISSUE TITLE
Not able to scroll down in Create Application home page

### ISSUE THREAD

**Issue by jyasveer** [fabric8-launcher/ngx-launcher#104]
Please see the screenshot below.
<img width="1440" alt="screen shot 2018-03-20 at 7 14 09 pm" src="https://user-images.githubusercontent.com/5430080/37658522-bcd2ac6c-2c73-11e8-9193-dca5d36ac5c4.png">

**Comment by edewit** [comment]
@jyasveer is this still an issue? Testing this on prod I have a scroll bar and I guess this is more a fabric8-ui issue anyway? closing for now
