### ISSUE TITLE
Runtime Summary Card Description Text Overflows Card

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-launcher/ngx-launcher#118]
In the "Confirm Application and Summary Setup" section, the Runtime card does not truncate the description. As a result, the text flows outside of the card.

<img width="1615" alt="screen shot 2018-03-28 at 8 44 38 am" src="https://user-images.githubusercontent.com/4032718/38029661-841b56fc-3264-11e8-80b0-7a155f2779e8.png">

**Comment by jyasveer** [comment]
@catrobson @mindreeper2420 @dgutride 
Any UX design we have for this scenario ? Please help me to find out here in this invision link 
https://redhat.invisionapp.com/share/VGF1RF15J#/screens/286900865

**Comment by mindreeper2420** [comment]
@jyasveer For now, the text should just truncate so that it does not overflow beyond the constraints of the card.

My suggestion would be to utilize the 'More' functionality as in the Mission/Runtime cards, but I will verify with Brian.

**Comment by bdellasc** [comment]
@jyasveer please take a look at the finalized text content doc [here](https://docs.google.com/document/d/1PRKPlg9zOgG9Eu5GZr96GCADPhPnLwZte0jkVx5q3KQ/edit?usp=sharing). The shortened runtime descriptions are on page 6.

**Comment by jyasveer** [comment]
thanks @bdellasc

**Comment by mindreeper2420** [comment]
closing
