### ISSUE TITLE
Indicate validation error in previous steps 

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/ngx-launcher#209]
Having a validation error like in:
![screenshot from 2018-05-15 12-00-40](https://user-images.githubusercontent.com/54133/40065238-b459c7ba-5837-11e8-88da-d86aef77f7e6.png)

And if I ignore that and scroll down directly to the end, I see that the Set Up Application button is disabled, but I don't know why
![screenshot from 2018-05-15 12-00-46](https://user-images.githubusercontent.com/54133/40065272-ca18f38c-5837-11e8-9257-9b346e0f6ba3.png)

Having an indication (changing the icon in the left side navigation bar with an error icon, for example) would help to determine what's wrong in the wizard steps

**Comment by gastaldi** [comment]
Ah, the Github card says "Incomplete", now I noticed that :smile: 
I was looking at the left side navigation bar to check what's wrong

**Comment by gastaldi** [comment]
In fact the card is kinda misleading. It isn't incomplete, it just has invalid values

**Comment by gastaldi** [comment]
@catrobson @dlabrecq @dgutride any thoughts on that?

**Comment by dlabrecq** [comment]
The section is considered incomplete because the user has not entered a valid GitGub repository. I'm assuming the error is displayed immediately, as the value is entered, and the down arrow button remains disabled?

IMO, an indication in the nav bar isn't a bad idea, but the user already has multiple indications that the section needs to be completed. The user should see the error message immediately, as they enter the GitHub repository, unless that's changed?

**Comment by gastaldi** [comment]
> I'm assuming the error is displayed immediately, as the value is entered, and the down arrow button remains disabled?

Yes, the error is displayed immediately, but you can click on the navigation bar instead of using the down arrow.

If the icon in the navbar changed to a warning/error sign, it would be more visible to the user that they need to navigate to that specific step I think

**Comment by catrobson** [comment]
@bdellasc - thoughts?

**Comment by bdellasc** [comment]
I'll noodle on it a bit and see where I land.

**Comment by bdellasc** [comment]
Here's my proposal for a section with error in the left panel + what that incomplete section with error looks like in the summary screen. I reviewed this with @catrobson.
![alt screen - oso - selected section error](https://user-images.githubusercontent.com/17882357/40135029-22fcea82-5912-11e8-834b-25ed39f6ade5.png)
![alt screen - oso - summary skipped steps 2](https://user-images.githubusercontent.com/17882357/40135030-230fb144-5912-11e8-8b7b-8db31b384e3d.png)

**Comment by gastaldi** [comment]
@bdellasc I loved it. 

@jyasveer can we get this implemented asap?

**Comment by ia3andy** [comment]
@bdellasc @jyasveer is there someone already working on this issue?

**Comment by bdellasc** [comment]
I'm not sure, but whenever someone does, I'd be happy to review it.

**Comment by ia3andy** [comment]
I will start to work on it on Tuesday (if nobody started it yet). Please let me know if someone already started until then.

**Comment by ia3andy** [comment]
This issue needs this first:
https://github.com/fabric8-launcher/ngx-launcher/issues/216

**Comment by slemeur** [comment]
Good for me.

**Comment by edewit** [comment]
fixed by #216
