### ISSUE TITLE
Switch to ngx-launcher npm package

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/ngx-launcher#324]
- [x] update package.json 
- [x] release `0.0.1` manually => https://www.npmjs.com/package/ngx-launcher
- [x] release `1.0.0` with semantic-release (locally)
- [x] setup semaphore-ci for PR and releases => https://semaphoreci.com/fabric8-launcher/ngx-launcher
- [x] add osio admins
- [x] update CI env `NPM_TOKEN` and `GH_TOKEN` with `fabric8cd` account

**Comment by gastaldi** [comment]
Since this is continuing ngx-forge, can we start with 1.0.0?

**Comment by ia3andy** [comment]
The switch to semaphore-ci is based on two main reasons:
- Get direct control over environements
- Get direct control of builds and releases
- centos-ci git version is too old to be used with latest semantic-release
