### ISSUE TITLE
Avoid making real requests in Demo

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/ngx-launcher#344]
In the demo, each time I click on a runtime/mission I have a failing POST request made to "http://0.0.0.0:8001/undefinedapi/v1/stack-analyses"
Demo is not supposed to make any real request.

cc @invincibleJai

**Comment by invincibleJai** [comment]
@ia3andy are you still seeing it? i tried both launcher and osio flow in standalone couldn't capture.

**Comment by ia3andy** [comment]
@invincibleJai Not seeing it anymore, weird.. did you change something in the dep editor?

**Comment by invincibleJai** [comment]
yes i observed this issue yesterday, so put the check in dep-checker component to load dep-editor component only if the flow is osio and feature flag is enabled for it 

https://github.com/fabric8-launcher/ngx-launcher/pull/340

**Comment by ia3andy** [comment]
@invincibleJai awesome closing then :)
