### ISSUE TITLE
If you scroll to summary step, Launch button is disabled even if every relevant steps are completed

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/ngx-launcher#362]
![image](https://user-images.githubusercontent.com/2223984/44519434-520eac80-a6cd-11e8-8c58-5e0797b365ab.png)

**Comment by vikram-raj** [comment]
@ia3andy Is all the move to next step button is highlighted? I am not able to reproduce this.

**Comment by ia3andy** [comment]
@vikram-raj I didn't get what you mean? It may be dependant of the system, I am using Chrome mac.
@edewit can you reproduce?

**Comment by edewit** [comment]
I can reproduce this, it takes some scrolling up and down, but then suddenly it's disabled and the last step is not valid anymore

**Comment by vikram-raj** [comment]
@ia3andy I am talking about this button 
![screenshot from 2018-08-24 15-09-10](https://user-images.githubusercontent.com/2561818/44577846-bbff8280-a7af-11e8-9be3-6d81829b1038.png)

If any of this button is disable and I scroll down to summary page then Set Up Application button is disabled for me.

**Comment by edewit** [comment]
also clicking a 'V' button when this happens will bring you to the status page without launch being started
![screenshot from 2018-08-24 11-52-59](https://user-images.githubusercontent.com/51133/44578908-0e7f7580-a795-11e8-9626-322b2e30482e.png)

**Comment by edewit** [comment]
@vikram-raj it's also happens when all the steps are completed and then still the 'review' step is disabled

1. to reproduce fill all the steps with valid data
1. scroll down and see that the button is enabled
1. click on the right on the other steps
1. Then the final button is disabled and will stay that way
