### ISSUE TITLE
Log in & Authorize button does not fail properly if backend responds with Gateway Timeout (408)

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/ngx-launcher#566]
Whenever there is a problem with the backend (usually called by a cluster instability) and a Gateway Timeout (408) is returned,  the UI doesn't perform properly when the Log in & Authorize button is clicked. 

It should display an error message indicating that the backend is not reachable at the moment.

See issue https://github.com/openshiftio/openshift.io/issues/4743 for more details

**Comment by christianvogt** [comment]
@vikram-raj could you please take a look at this

**Comment by vikram-raj** [comment]
@christianvogt This PR https://github.com/fabric8-launcher/ngx-launcher/pull/569 should fix this issue.
@gastaldi Can you please verify?

**Comment by gastaldi** [comment]
@vikram-raj I haven't been able to reproduce the issue, but your PR looks alright. I'll close it and reopen if the problem persists
